version: '3.5'
services: 
  bqaiq-website:
    container_name: bqaiq-website
    build: 
      context: ./
      dockerfile: Dockerfile
    restart: always
    # image: optics.azurecr.io/optics-frontend:1.5.0-mahmoud
    ports: 
      - '1200:3000'