const Types = {
    //SignIn Popup Show Controller
    TOGGLE_SIGNIN_POPUP: 'TOGGLE_SIGNIN_POPUP',

    // show or hide spinner
    TOGGLE_SPINNER: 'TOGGLE_SPINNER',


    //Authentication
    // REGISTER_NEW_USER: 'REGUSTER_NEW_USER',
    SIGNEDIN_USERDATA: 'SIGNEDIN_USERDATA',
    VERIFY_MOBILE: 'VERIFY_MOBILE',
    VERIFY_EMAIL: 'VERIFY_EMAIL',
    FORGET_PASSWORD: 'FORGET_PASSWORD',
    VERIFY_RESET_CODE: 'VERIFY_RESET_CODE',
    RESET_PASSWORD: 'RESET_PASSWORD',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    CLEAN_UP_RESET_DATA: 'CLEAN_UP_RESET_DATA',
    LOG_OUT: 'LOG_OUT',

    // who-we-are page
    GET_WHO_WE_ARE: 'GET_WHO_WE_ARE',
    GET_PRAISE_DETAILS: 'GET_PRAISE_DETAILS',
    CLEAN_PRAISE_DETAILS: 'CLEAN_PRAISE_DETAILS',
    // GET_OUR_GOALS: 'GET_OUR_GOALS',

    // our projects page
    GET_OUR_PROJECTS: 'GET_OUR_PROJECTS',

    // lessons page
    GET_LESSONS: 'GET_LESSONS',
    GET_LESSON_DETAILS: 'GET_LESSON_DETAILS',
    GET_ALL_SHEIKHS: 'GET_ALL_SHEIKHS',
    GET_SHEIKH_DETAILS: 'GET_SHEIKH_DETAILS',

    // el-galiat page
    GET_ELGALIAT: 'GET_ELGALIAT',

    // videos page
    GET_VIDEOS: 'GET_VIDEOS',

    // women section
    GET_WOMEN_SECTION: 'GET_WOMEN_SECTION',

    //bookstore
    GET_BOOKSTORE: 'GET_BOOKSTORE',
    GET_BOOK_DETAILS: 'GET_BOOK_DETAILS',

    //media center
    GET_MEDIA_CENTER_SECTION: 'GET_MEDIA_CENTER_SECTION',
    GET_POST_DETAILS: 'GET_POST_DETAILS',
    CLEAN_POST_DETAILS: 'CLEAN_POST_DETAILS',

    // donnation page
    GET_DONNATION_LIST_OF_PROJECT: 'GET_DONNATION_LIST_OF_PROJECT',

    // home page
    GET_BANNERS: 'GET_BANNERS',
    GET_HOME_DATA: 'GET_HOME_DATA',

    //anti-terrorism
    GET_EFFORTS: 'GET_EFFORTS',
    GET_SUSPICIONS: 'GET_SUSPICIONS',
    GET_RESEARCH: 'GET_RESEARCH',
    GET_VIDEOS: 'GET_VIDEOS',
    GET_AUDIOS: 'GET_AUDIOS',
}
export default Types;